module.exports = [
    {
        "name": "Bread omelette",
        "ingredients": "<h3>Ingredients</h3><ol><li>Modern Foods 100% Whole Wheat Brown Bread – <i><strong>2 Slices</strong></i></li><li>Eggs – <i><strong>1 Large or 2 Small</strong></i></li><li>Oil – <i><strong>1.5 tsp (you may also use a single square of butter)</strong></i></li><li>Green Chilli – <i><strong>1, finely chopped</strong></i></li><li>Onion, finely chopped – <i><strong>1 tbsp</strong></i></li><li>Capsicum, finely chopped – <i><strong>1 tbsp</strong></i></li><li>Salt – <i><strong>as per taste</strong></i></li><li>Pepper – <i><strong>as per taste</strong></i></li><li>Chaat masala – <i><strong>as per taste</strong></i></li><li>Sandwich spread or Ketchup</li><li>Grated cheese or cheese slice</li></ol>",
        "instructions": "<h3>Method</h3><ol><li>Whisk the egg in a bowl till the mix turns frothy.</li><li>Add the veggies, green chillies, followed by the desired seasoning, and mix well.</li><li>Add your oil to a flat cooking pan, and let it heat.</li><li>Drop the egg mixture onto the heated pan, spread it uniformly and let it cook for 2 minutes on medium flame. Flip the omelette once the sides start browning and the surface looks half cooked. Lift the omelette up from the flat pan.</li><li>Place one slice of bread on the same pan to toast it.Meanwhile, place the omelette on top of the bread and fold it in a square shape. You may alternatively first place the cheese slice/grated cheese in the middle before folding it in. Allow the cheese to melt.</li><li>Place the other bread slice on top and then flip it so that the other bread slice gets toasted.</li><li>Once the surface crisps up, take it off heat.</li><li>Slice the sandwich into half and serve warm.</li></ol><p><span style='color:#f44336;'>Serve it with tomato sauce or green chutney for an unforgettable experience!</span></p>",
        "duration": "10 minutes",
        "category": "Breakfast",
        "images": ["https://www.themealdb.com//images//media//meals//hqaejl1695738653.jpg","https://www.modernfoods.co.in/wp-content/uploads/2018/09/breadomellete555.png", "https://b2958125.smushcdn.com/2958125/wp-content/uploads/bread-omelette-recipe-1-5.jpg?lossy=1&strip=1&webp=1"]
    },

    {
        "name": "Paneer Toast",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>Modern Foods 100% Whole Wheat Rusk: 6</li><li>Paneer: 1 bowl, grated</li><li>Tomato Ketchup or Sauce of your choice: 1 tsp</li><li>Tomato: 1, small, finely chopped</li><li>Red chilli powder: ½ tsp</li><li>Garlic Bread Seasoning: as per taste</li><li>Salt: as per taste</li><li>Finely chopped coriander</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ol><li>Add your flavours and seasoning – salt, red chilli powder, garlic bread seasoning – and mix well.</li><li>Then add your ketchup or any other sauce of your preference and mix well.</li><li>If you like your paneer sautéed, don’t hesitate in frying some cottage cheese in a lightly heated pan for that mild crunch.</li><li>Spread the mix evenly on the rusk toast</li><li>Garnish with tomatoes and coriander</li><li>Consume fresh</li></ol></span></div>",
        "duration": "10 minutes",
        "category": "Breakfast",
        "images": ["https://www.modernfoods.co.in/wp-content/uploads/2018/09/pannertoast555.png","https://www.bing.com/images/search?view=detailV2&ccid=hvQpFwbd&id=6DF2057C113D1E21630128DBA53B3334B4794CD4&thid=OIP.hvQpFwbd1cU-CmLuws4gCAHaLH&mediaurl=https%3a%2f%2fwww.cookingclassy.com%2fwp-content%2fuploads%2f2019%2f09%2fgarlic-bread-04.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.86f4291706ddd5c53e0a62eec2ce2008%3frik%3d1Ex5tDQzO6XbKA%26pid%3dImgRaw%26r%3d0&exph=1800&expw=1200&q=garlic+bread+recipe&simid=608001996406873013&FORM=IRPRST&ck=80E97867A92D7D762BF66B1C84F85FFD&selectedIndex=0&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=%2f43np%2fhN&id=F42C26D4E194208A1EE6B3D4757DF0D8B2F78703&thid=OIP._43np_hNRzn3yPZqfK67FgHaE7&mediaurl=https%3a%2f%2f4.bp.blogspot.com%2f-hw0YORhc-tk%2fWp5wg88U-dI%2fAAAAAAAACuk%2f_Irr5fywwtE0S2PB12OhlqfAoju2mMQDACEwYBhgL%2fs1600%2fBread%252BPaneer%252BPakora%252B-%252BStreet%252BFood%252BSnack%252BRecipe%252B%2525282%252529.JPG&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.ff8de7a7f84d4739f7c8f66a7caebb16%3frik%3dA4f3stjwfXXUsw%26pid%3dImgRaw%26r%3d0&exph=1066&expw=1600&q=paneer+bread&simid=608012596373556007&FORM=IRPRST&ck=C08315DD5F9AD3DB3B86FC6A037A881F&selectedIndex=2&itb=0"]
    },

    {
        "name": "Classic Margherita Pizza",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>Modern Foods Whole Wheat Pizza Base – 1</li><li>Olive Oil – 1 Tbsp</li><li>Garlic, roasted &amp; finely chopped – 2 Cloves</li><li>Mozzarella/Pizza cheese – 200 g, cut into slices</li><li>Tomatoes, sliced – 2</li><li>Fresh basil leaves – a handful</li><li>Pizza Sauce – 1/4th cup</li><li>Freshly ground pepper – as per taste</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ul><li>Preheat the oven to 200 C.</li><li>Mix the garlic and the olive oil together. Using a pastry brush, brush it lightly on the pizza base.</li><li>Add your pizza sauce. Be careful and spread it uniformly.</li><li>Spread the mozzarella slices on top, then further add the tomato slices.</li><li>Bake the pizza on grease proof sheet for 10-15 minutes or till the crust starts browning and cheese starts bubbling.</li><li>Remove the pizza from the oven, and while still warm add the basil and season with pepper.</li><li>Serve hot.</li></ul></span></div>",
        "duration": "10 minutes",
        "category": "Breakfast",
        "images": ["https://www.modernfoods.co.in/wp-content/uploads/2018/06/360pizza.png","https://www.bing.com/images/search?view=detailV2&ccid=WvD5iGRc&id=9E5D366F5D04F26A34DFDE0F6ECA91536AB60258&thid=OIP.WvD5iGRciq3ykcyCIi0U6wHaHa&mediaurl=https%3a%2f%2frecipes.timesofindia.com%2fphoto%2f56868564.cms&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.5af0f988645c8aadf291cc82222d14eb%3frik%3dWAK2alORym4P3g%26pid%3dImgRaw%26r%3d0&exph=1200&expw=1200&q=Classic+Margherita+Pizza&simid=608002129526002653&FORM=IRPRST&ck=7AEB001106FC7101E30B9B010ECCF49E&selectedIndex=17&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=xUd3gsrJ&id=7560E9F2CA20BB7A38CEB53F6EA3230738B012CA&thid=OIP.xUd3gsrJjG--lvuuv3R2rwHaLF&mediaurl=https%3a%2f%2fhomemadehooplah.com%2fwp-content%2fuploads%2f2017%2f11%2fClassic-Margherita-Pizza-1.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.c5477782cac98c6fbe96fbaebf7476af%3frik%3dyhKwOAcjo24%252ftQ%26pid%3dImgRaw%26r%3d0&exph=1198&expw=800&q=Classic+Margherita+Pizza&simid=608028363214773225&FORM=IRPRST&ck=3669220E6590CB1D94D4DA3A3C9E0B95&selectedIndex=0&itb=0"]
    },

    {
        "name": "Healthy Bread Salad",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>Modern Multigrain Superseed Bread Slices- 4-5</li><li>Tomatoes- 2 medium. Diced, de-seeded</li><li>Cucumber- 1 medium, diced</li><li>Paneer- 6-7 medium cubes</li><li>Corns- ¾ cup</li><li>Broccoli (optional)</li><li>Olive Oil- 2 table spoons (optional)</li><li>Refined Oil- 2 tablespoon</li><li>Black Pepper -1/2 tea spoon</li><li>Cream or mayonnaise (Optional)</li><li>Lemon- Half</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ol><li>Spread two spoons refined oil on hot frying pan, toast the bread slices till they turn brown. (You can even deep fry them if you want). Cut the bread slices in small or long pieces as you like.</li><li>Blanch broccoli and corns for 5 minutes. Keep aside.</li><li>Layer a large bowl with olive oil. Add all chopped veggies, crispy bread cubes, paneer cubes, blanched broccoli and corns.</li><li>Add a dollop of mayo or cream. Those who are health conscious can skip it and replace with squeezing half a lemon.</li><li>Whisk all ingredients together. Add black pepper.(Olive oil is not necessary in case you don’t have it)</li></ol></span></div>",
        "duration": "5 minutes",
        "category": "Breakfast",
        "images": ["https://www.modernfoods.co.in/wp-content/uploads/2017/05/Healthy-Bread-Salad-innner.jpg","https://www.bing.com/images/search?view=detailV2&ccid=Q99Y6qTK&id=0AB868F4D8652361AD8568754483A7F3A0A51842&thid=OIP.Q99Y6qTKotn5zqMXw30C4wHaFj&mediaurl=https%3a%2f%2fimages.eatsmarter.com%2fsites%2fdefault%2ffiles%2fstyles%2f1024x768%2fpublic%2fbread-salad-563518.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.43df58eaa4caa2d9f9cea317c37d02e3%3frik%3dQhiloPOng0R1aA%26pid%3dImgRaw%26r%3d0&exph=768&expw=1024&q=Healthy+Bread+Salad&simid=608031919450101796&FORM=IRPRST&ck=FF9CDA92226154FAF0606D9B49F9A2AD&selectedIndex=3&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=Q5jaT%2ba1&id=DFBF048F4705F5418AB331375DE64A0501011255&thid=OIP.Q5jaT-a1fQNrC9HJ-xv1LQHaHa&mediaurl=https%3a%2f%2ftwomarketgirls.com%2fwp-content%2fuploads%2f2020%2f08%2fIMG_8943.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.4398da4fe6b57d036b0bd1c9fb1bf52d%3frik%3dVRIBAQVK5l03MQ%26pid%3dImgRaw%26r%3d0&exph=1420&expw=1420&q=Healthy+Bread+Salad&simid=608005024337649152&FORM=IRPRST&ck=9115E5CC5361450A6EAE861D0DD3A88D&selectedIndex=7&itb=0"]
    },

    {
        "name": "Grated Veggie Sandwich",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>Modern 100% Whole Wheat Bread-4</li><li>1 medium carrot- grated</li><li>1 medium cucumber-grated</li><li>1 medium tomato – Thin slices</li><li>Cheese spread or butter</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ol><li>Spread butter or cheese spread on bread.</li><li>Layer the grated veggies and thin slices of tomatoes</li><li>Grill the sandwich or toast on tava. Enjoy a healthy sandwich filled with grated veggies.</li></ol></span></div>",
        "duration": "10 minutes",
        "category": "Breakfast",
        "images": ["https://www.modernfoods.co.in/wp-content/uploads/2017/05/Veggie-Sandwich-inner.jpg","https://www.bing.com/images/search?view=detailV2&ccid=Y5e0%2fBz3&id=8AFCA13E10E5C3B5159AEB3CFCE0858C76433B0A&thid=OIP.Y5e0_Bz36nsY9H_JtA02aAHaFj&mediaurl=https%3a%2f%2fi.pinimg.com%2foriginals%2fa5%2ff2%2f10%2fa5f21054fcc0f406d154a1d151fa1f04.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.6397b4fc1cf7ea7b18f47fc9b40d3668%3frik%3dCjtDdoyF4Pw86w%26pid%3dImgRaw%26r%3d0&exph=1650&expw=2200&q=Grated+Veggie+Sandwich&simid=608029235086516328&FORM=IRPRST&ck=E9759E3603BD2741BC9B4B85AEA903EC&selectedIndex=15&itb=0"]
    },

    {
        "name": "Bread Aaloo Tikki",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>7-8 Modern Multi Grain Super Seed Bread slices</li><li>3 medium sized potatoes- boiled, peeled</li><li>2-3 green chillies- chopped</li><li>&nbsp;Few coriander leaves</li><li>1 tsp. Red chilli powder</li><li>Salt to taste</li><li>2 cups oil (for deep frying)</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ol><li>Mash boiled potatoes. Mix with salt, green chillies, red chilli powder &amp; coriander leaves.</li><li>Dip bread slices in water. Gently squeeze out water. Mash the soaked bread slices with potato mixture.</li><li>Make round balls of the mixture and flatten them in shape of tikki.</li><li>Heat oil. Deep fry the tikkis.</li><li>Serve with green or red chutney.</li></ol></span></div>",
        "duration": "20 minutes",
        "category": "Breakfast",
        "images": ["https://www.modernfoods.co.in/wp-content/uploads/2017/07/bread-aloo-tikki-1.jpg","https://www.bing.com/images/search?view=detailV2&ccid=0dKAWWaA&id=885467C4ACB1A355C32AA82B222C5E647956F1D8&thid=OIP.0dKAWWaAqN52LZbAv_AdXAHaHa&mediaurl=https%3a%2f%2fwww.cubesnjuliennes.com%2fwp-content%2fuploads%2f2020%2f08%2fCrispy-Aloo-Tikki-Recipe.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.d1d280596680a8de762d96c0bff01d5c%3frik%3d2PFWeWReLCIrqA%26pid%3dImgRaw%26r%3d0&exph=1201&expw=1200&q=Bread+Aaloo+Tikki&simid=608013038760306830&FORM=IRPRST&ck=398A51E8B89A63FD8653F699A0B485A8&selectedIndex=1&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=sb8iUCXs&id=CBC1A4CE442F11813F77DBD07962F0D878E7556F&thid=OIP.sb8iUCXs9NI8tdDJbUXSFQHaGN&mediaurl=https%3a%2f%2fwww.zaykakatadka.com%2fwp-content%2fuploads%2f2020%2f08%2fBread-Aloo-Tikki.png&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.b1bf225025ecf4d23cb5d0c96d45d215%3frik%3db1XneNjwYnnQ2w%26pid%3dImgRaw%26r%3d0&exph=788&expw=940&q=Bread+Aaloo+Tikki&simid=608029406908936823&FORM=IRPRST&ck=637862944789A79CC3DBD5E6FB88A773&selectedIndex=9&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=Q%2fq%2f%2fSws&id=1201E01EB4A0A0607FCC2891107DBF1BB290CCD5&thid=OIP.Q_q__SwsYcSZLOf2uSJJIQHaEK&mediaurl=https%3a%2f%2fi.ytimg.com%2fvi%2fvkINDNxKRBM%2fmaxresdefault.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.43fabffd2c2c61c4992ce7f6b9224921%3frik%3d1cyQshu%252ffRCRKA%26pid%3dImgRaw%26r%3d0&exph=720&expw=1280&q=Bread+Aaloo+Tikki&simid=608050190209460964&FORM=IRPRST&ck=D0A66BE98D6FB255840D6FC95360056C&selectedIndex=23&itb=0"]
    },

    {
        "name": "Grilled Pork Tenderloin and Asparagus With Mustard-Herb Sauce",
        "ingredients": "<div class='List-iSNGTT ljAYJm'><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>2 tsp. fennel seeds</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>¼ tsp. smoked paprika</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>1½ tsp. Diamond Crystal kosher salt, divided</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>2 pork tenderloins (about 2 lb.), silverskins trimmed</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>1 garlic clove, finely grated</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>5 Tbsp. extra-virgin olive oil</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>2 Tbsp. sherry vinegar</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>2 Tbsp. whole-grain Dijon mustard</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>½ cup (packed) parsley leaves, finely chopped</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>Canola oil (for grill grate)</div><div class='BaseWrap-sc-gjQpdd BaseText-ewhhUZ Description-cSrMCf iUEiRd kwRQkr fsKnGI'>2 bunches asparagus, trimmed</div></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ul><li>Preheat the oven to 200 C.</li><li>Mix the garlic and the olive oil together. Using a pastry brush, brush it lightly on the pizza base.</li><li>Add your pizza sauce. Be careful and spread it uniformly.</li><li>Spread the mozzarella slices on top, then further add the tomato slices.</li><li>Bake the pizza on grease proof sheet for 10-15 minutes or till the crust starts browning and cheese starts bubbling.</li><li>Remove the pizza from the oven, and while still warm add the basil and season with pepper.</li><li>Serve hot.</li></ul></span></div>",
        "duration": "35 minutes",
        "category": "Lunch",
        "images": ["https://assets.epicurious.com/photos/644fd76a90edaa1540a53f10/1:1/w_1920,c_limit/GrilledPorkAsparagus_RECIPE_042723_52862.jpg","https://www.bing.com/images/search?view=detailV2&ccid=1SNTL9sy&id=40B1D3EF5F5B3FD12224158AF88A1375D0D94E51&thid=OIP.1SNTL9syGnISZwSr-MZFEQHaJQ&mediaurl=https%3a%2f%2fcravinghomecooked.com%2fwp-content%2fuploads%2f2021%2f05%2fpork-tenderloin-with-mustard-sauce-1.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.d523532fdb321a72126704abf8c64511%3frik%3dUU7Z0HUTiviKFQ%26pid%3dImgRaw%26r%3d0&exph=1500&expw=1200&q=Grilled+Pork+Tenderloin+and+Asparagus+With+Mustard-Herb+Sauce&simid=608037305336747043&FORM=IRPRST&ck=51EB1A3391C6AF41AC4D6845B71F3A7C&selectedIndex=4&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=PuOA6V1u&id=3E204CC9CD0480D39BEF1963865572C300CB6B01&thid=OIP.PuOA6V1u4Sp10AkuCq8-EAHaHf&mediaurl=https%3a%2f%2fwww.bentcreekwinery.com%2fwp-content%2fuploads%2f2020%2f04%2frecipe02.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.3ee380e95d6ee12a75d0092e0aaf3e10%3frik%3dAWvLAMNyVYZjGQ%26pid%3dImgRaw%26r%3d0&exph=688&expw=680&q=Grilled+Pork+Tenderloin+and+Asparagus+With+Mustard-Herb+Sauce&simid=608010582059216287&FORM=IRPRST&ck=78664DB10A0A928AEA036A92B221FA4E&selectedIndex=7&itb=0"]
    },

    {
        "name": "Tater Tot Chaat",
        "ingredients": "<div class='col-sm-6'><h3>Ingredients</h3> <span itemprop='recipeIngredient'><ul><li>Modern Foods Whole Wheat Pizza Base – 1</li><li>Olive Oil – 1 Tbsp</li><li>Garlic, roasted &amp; finely chopped – 2 Cloves</li><li>Mozzarella/Pizza cheese – 200 g, cut into slices</li><li>Tomatoes, sliced – 2</li><li>Fresh basil leaves – a handful</li><li>Pizza Sauce – 1/4th cup</li><li>Freshly ground pepper – as per taste</li></ul></span></div>",
        "instructions": "<div class='col-sm-6'><h3>Method</h3> <span itemprop='recipeInstructions'><ol><li>Mash boiled potatoes. Mix with salt, green chillies, red chilli powder &amp; coriander leaves.</li><li>Dip bread slices in water. Gently squeeze out water. Mash the soaked bread slices with potato mixture.</li><li>Make round balls of the mixture and flatten them in shape of tikki.</li><li>Heat oil. Deep fry the tikkis.</li><li>Serve with green or red chutney.</li></ol></span></div>",
        "duration": "45 minutes",
        "category": "Lunch",
        "images": ["https://assets.epicurious.com/photos/65e105ccff0094f439ea88c0/1:1/w_1920,c_limit/Tater-Tot-Chaat_RECIPE.jpg","https://th.bing.com/th/id/OIP.PVLtBHGHYhfeKEReUZVLSQHaLG?rs=1&pid=ImgDetMain", "https://th.bing.com/th/id/OIP.l4TOZFNpsqoxDbXR1aPhtwHaLG?rs=1&pid=ImgDetMain"]
    },

    {
        "name": "Penne Alla Vodka With Bacon",
        "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->2<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>½ lb <!-- -->dried penne pasta<span class='xs-inline-block xs-ml05'> (<!-- -->225 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>4 strips <!-- -->bacon<!-- -->, finely diced</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->unsalted butter<!-- -->, divided</li><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->large shallot<!-- -->, finely diced</li><li class='ingredient xs-mb1 xs-mt0'>½ teaspoon <!-- -->red pepper flakes</li><li class='ingredient xs-mb1 xs-mt0'>4 cloves <!-- -->garlic<!-- -->, minced</li><li class='ingredient xs-mb1 xs-mt0'>3 tablespoons <!-- -->vodka</li><li class='ingredient xs-mb1 xs-mt0'>1 can <!-- -->crushed san marzano tomato<!-- -->, pushed through a fine-mesh strainer</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->kosher salt</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->freshly ground black pepper</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->heavy cream<span class='xs-inline-block xs-ml05'> (<!-- -->120 <!-- -->mL<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->butter</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->grated parmesan cheese<span class='xs-inline-block xs-ml05'> (<!-- -->55 <!-- -->g<!-- -->)</span>, and romano cheeses</li></ul></div></div>",
        "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Bring a large pot of salted water to a boil. Add the penne and cook according to the package instructions until al dente. Reserve 1 cup of the pasta water, then drain the pasta and rinse under cold water.</li><li class='xs-mb2'>Heat a large saucepan over medium-high heat. Add the bacon and cook until the edges are crisp, 2–3 minutes. If bacon is not particularly fatty, add 1 tablespoon of butter and stir until melted. Add the shallot and cook until softened, 3–4 minutes. Add the garlic and red pepper flakes and cook until fragrant, about 30 seconds.</li><li class='xs-mb2'>Add the vodka and cook until almost completely evaporated, 1–2 minutes. Add the crushed tomatoes, pepper, and salt. Bring to a simmer, then cook for 4 minutes, or until the sauce the mixture comes to a low boil. Add the cream, reduce the heat to low, and simmer for 5 minutes, until the sauce has thickened.</li><li class='xs-mb2'>Add the penne and remaining tablespoon of butter and stir until well coated in the sauce. If the sauce is too thick, add a splash of the reserved pasta water.</li><li class='xs-mb2'>Remove the pan from the heat. Add the Parmesan and Romano cheeses and stir until incorporated.</li><li class='xs-mb2'>Transfer the pasta to a serving dish and top with torn burrata, a drizzle of olive oil, pepper, and basil.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
        "duration": "25 minutes",
        "category": "Lunch",
        "images": ["https://img.buzzfPenne Alla Vodka With Baconed.com/video-api-prod/assets/8153374d2a484d6f95196d4d378a6aad/chicken_and_broccoli_alfredo_FB_thumb.jpg?resize=600:*&output-format=auto&output-quality=auto","https://www.bing.com/images/search?view=detailV2&ccid=hYveclJu&id=1B790DC778F84FD96F80A59D4FD0A58D0B2F2FF0&thid=OIP.hYveclJu56uMHNPbYyZBWwHaLH&mediaurl=https%3a%2f%2fwww.cookingclassy.com%2fwp-content%2fuploads%2f2020%2f01%2fpenne-alla-vodka-9.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.858bde72526ee7ab8c1cd3db6326415b%3frik%3d8C8vC42l0E%252bdpQ%26pid%3dImgRaw%26r%3d0&exph=1800&expw=1200&q=Penne+Alla+Vodka+With+Bacon&simid=608030111275633263&FORM=IRPRST&ck=AD824ECB212C4C63E05DC7255113BDE7&selectedIndex=4&itb=0", "https://www.bing.com/images/search?view=detailV2&ccid=CupxXAcy&id=8BA1353A29AC62BABCDD6CE9FC1FA0108FE6B72E&thid=OIP.CupxXAcyliheeAx5OaQxKQHaJ4&mediaurl=https%3a%2f%2frecipebinge.com%2fwp-content%2fuploads%2f2021%2f07%2fSuper-Creamy-Penne-Alla-Vodka-9-1536x2048.jpg&cdnurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.0aea715c073296285e780c7939a43129%3frik%3dLrfmjxCgH%252fzpbA%26pid%3dImgRaw%26r%3d0&exph=2048&expw=1536&q=Penne+Alla+Vodka+With+Bacon&simid=608036515066109882&FORM=IRPRST&ck=D9DF46B05D1C85738BD400BAACBA4C36&selectedIndex=8&itb=0"]
    },

    {
        "name": "Veggie Fried Rice",
        "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->4<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 teaspoons <!-- -->neutral oil</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->diced carrot<span class='xs-inline-block xs-ml05'> (<!-- -->60 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->diced yellow onion<span class='xs-inline-block xs-ml05'> (<!-- -->75 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->minced garlic</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->diced bell pepper<span class='xs-inline-block xs-ml05'> (<!-- -->50 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->broccoli florets<span class='xs-inline-block xs-ml05'> (<!-- -->75 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>3 <!-- -->large eggs<!-- -->, beaten</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->peas<span class='xs-inline-block xs-ml05'> (<!-- -->75 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>⅓ cup <!-- -->corn</li><li class='ingredient xs-mb1 xs-mt0>3 cups <!-- -->cooked white rice<span class='xs-inline-block xs-ml05'> (<!-- -->600 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->soy sauce</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->sesame oil</li><li class='ingredient xs-mb1 xs-mt0'>freshly ground black pepper<!-- -->, to taste</li></ul></div><div></div></div>",
        "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>In a wok or deep skillet, heat the oil over high heat until shimmering. Add the carrot, onion, and garlic and cook until the onion is translucent.</li><li class='xs-mb2'>Add the bell peppers and broccoli and cook for 3-4 minutes, until tender. Push the cooked vegetables to the sides of the pan.</li><li class='xs-mb2'>Pour the beaten eggs into the empty part of the pan. Stir until scrambled, then mix in with the vegetables.</li><li class='xs-mb2'>Add the peas, corn, rice, soy sauce, sesame oil, and black pepper. Mix well, then let the rice cook until slightly crispy.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
        "duration": "20 minutes",
        "category": "Lunch",
        "images": ["https://img.buzzfeed.com/thumbnailer-prod-us-east-1/97aa9be31408452591baef80ebc6b52c/BFV24904_FriedRice4Ways_FB1080SQ.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.9aoqWQnzKwDmXe-tC4wtzgHaHa?w=187&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7", "https://th.bing.com/th/id/OIP.jZpZvRcp_ZaFWDHX7UJFdAHaLH?rs=1&pid=ImgDetMain"]
    },
{
    "name": "Bread Chocolate Chip Cookie",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->1<!-- --> <!-- -->cookie</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->unsalted butter<!-- -->, softened, plus more for greasing</li><li class='ingredient xs-mb1 xs-mt0'>¼ cup <!-- -->light brown sugar<span class='xs-inline-block xs-ml05'> (<!-- -->55 <!-- -->g<!-- -->)</span>, lightly packed</li><li class='ingredient xs-mb1 xs-mt0'>½ teaspoon <!-- -->vanilla extract</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->egg<!-- -->, beaten</li><li class='ingredient xs-mb1 xs-mt0'>6 tablespoons <!-- -->all purpose flour</li><li class='ingredient xs-mb1 xs-mt0'>⅛ teaspoon <!-- -->kosher salt</li><li class='ingredient xs-mb1 xs-mt0'>5 ½ tablespoons <!-- -->semi-sweet chocolate chips<!-- -->, divided</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Grease a large (at least 8-inch (20 cm) diameter) microwave-safe plate with butter.</li><li class='xs-mb2'>In a medium bowl, use a whisk or fork to stir together the butter, sugar. Add vanilla extract.</li><li class='xs-mb2'>Add the egg and stir to combine.</li><li class='xs-mb2'>Add the flour and salt and stir until just incorporated</li><li class='xs-mb2'>Fold in 5 tablespoons of the chocolate chips.</li><li class='xs-mb2'>Scoop the dough into a mound at the center of the prepared plate. Lightly press the remaining chocolate chips into the top of the dough.</li><li class='xs-mb2'>Microwave until the cookie is dry on top and springs back when lightly pressed in the center, about 1½ minutes. Let sit for a few minutes to cool.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
    "duration": "15 minutes",
    "category": "Lunch",
    "images": ["https://img.buzzfeed.com/thumbnailer-prod-us-east-1/7b394313d62b45bca9dd00229e954f01/BFV57556_2min2hr2dayCookies-YT.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.uRAra8YhE1e0v5QqsxHc5wHaLH?rs=1&pid=ImgDetMain", "https://th.bing.com/th/id/OIP.4nxdSKlyxaCDGM8X8nUllwHaKX?rs=1&pid=ImgDetMain"]
},
{
    "name": "Sweet Potato Fries",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->2<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->medium sweet potato</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->olive oil</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->fresh rosemary<!-- -->, chopped</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->salt</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->freshly ground black pepper</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Preheat oven to 425ºF/220ºC.</li><li class='xs-mb2'>Slice the ends off of the sweet potato and then slice it in half. Take one half and slice it horizontally 4 times then slice vertically 4 times to cut into fries.</li><li class='xs-mb2'>In a large bowl mix fries and ingredients until evenly spread.</li><li class='xs-mb2'>Place fries on a prepared baking sheet and bake for 25 minutes or until fluffy inside and crunchy on the outside.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
    "duration": "30 minutes",
    "category": "Lunch",
    "images": ["https://img.buzzfeed.com/thumbnailer-prod-us-east-1/e35181917389415d85893e54e2b40099/Tasty_Vegetarian_-_Facebook_-_1080x1080.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.q9nenmBwlZr7ec5jmB4U2QHaLH?rs=1&pid=ImgDetMain", "https://th.bing.com/th/id/OIP.fzIdnOfyrb7jLXYuaMIPEQAAAA?rs=1&pid=ImgDetMain"]
},
{
    "name": "Grilled Cheese Orbs With Knight’s Ketchup",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->12<!-- --> <!-- -->orbs</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>1 loaf <!-- -->brioche bread<!-- -->, sliced</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->cheddar cheese<span class='xs-inline-block xs-ml05'> (<!-- -->65 <!-- -->g<!-- -->)</span>, cut into ¾” inch (2 cm) cubes</li><li class='ingredient xs-mb1 xs-mt0'>2 cloves <!-- -->garlic<!-- -->, finely minced</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->fresh parsley<!-- -->, finely minced</li><li class='ingredient xs-mb1 xs-mt0'>6 tablespoons <!-- -->butter</li><li class='ingredient xs-mb1 xs-mt0'>¼ cup <!-- -->grated parmesan cheese<span class='xs-inline-block xs-ml05'> (<!-- -->30 <!-- -->g<!-- -->)</span></li></ul></div><div class='ingredients__section xs-mt1 xs-mb3'><p class='ingredient-section-name xs-text-5 extra-bold caps xs-mb1'>Ketchup:</p><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->ketchup<span class='xs-inline-block xs-ml05'> (<!-- -->120 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>¼ teaspoon <!-- -->allspice</li><li class='ingredient xs-mb1 xs-mt0'>¼ teaspoon <!-- --> sriracha</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Preheat your oven to 400 degrees. Begin by taking a slice of brioche, then place one of the cheese cubes in the center. Enclose the bread around the cheese and squeeze in your hands to seal, rolling around to form a spherical shape. Repeat with the rest of the slices of bread and cheese. Place on a sheet tray and bake in the oven for 8 - 10 minutes, or until golden brown.</li><li class='xs-mb2'>While the orbs bake, melt the butter, garlic, parsley, and cheese together in a pot over medium low heat, then set aside. Next, combine the ketchup, allspice, and sriracha in a mixing bowl and whisk well to combine, then set aside.</li><li class='xs-mb2'>When the orbs are done, remove from the oven then use a pastry brush to spread the parsley garlic butter all over each orb. Transfer to your serving platter and top with some extra parmesan cheese and parsley. Serve with the ketchup.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
    "duration": "20 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/385613.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.Y5y_I0vkQPW4ovuCDAgrHQHaLH?rs=1&pid=ImgDetMain", "https://th.bing.com/th/id/R.3fd79e2725f3627207739f2bf97c335a?rik=jQg0Lv%2f8jMSzzg&pid=ImgRaw&r=0"]
},
{
    "name": "Black Bean Burgers",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->4<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 cans <!-- -->black beans<!-- -->, rinsed and drained</li><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->onion<!-- -->, minced</li><li class='ingredient xs-mb1 xs-mt0'>3 cloves <!-- -->garlic<!-- -->, minced</li><li class='ingredient xs-mb1 xs-mt0'>2 <!-- -->carrots<!-- -->, shredded</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->quick-cooking oats<span class='xs-inline-block xs-ml05'> (<!-- -->50 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->soy sauce</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->olive oil</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->cumin</li><li class='ingredient xs-mb1 xs-mt0'>½ teaspoon <!-- -->coriander</li><li class='ingredient xs-mb1 xs-mt0'>½ teaspoon <!-- -->chili powder</li><li class='ingredient xs-mb1 xs-mt0'>¼ teaspoon <!-- -->cayenne pepper</li><li class='ingredient xs-mb1 xs-mt0'>salt<!-- -->, to taste</li><li class='ingredient xs-mb1 xs-mt0'>pepper<!-- -->, to taste</li><li class='ingredient xs-mb1 xs-mt0'>4 <!-- -->buns of choice</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Heat one tablespoon of olive oil in a pan. Combine onions, garlic, salt, and pepper and cook until onions are translucent.</li><li class='xs-mb2'>Add carrots, cumin, coriander, chili powder, and cayenne pepper until carrots are tender. Remove pan from heat.</li><li class='xs-mb2'>In a bowl, mash the beans and then add the contents of the pan along with the soy sauce and quick oats.</li><li class='xs-mb2'>Mix and form four patties. Place in freezer for 30 minutes to set.</li><li class='xs-mb2'>Cook patties on a pan coated in cooking spray over medium heat, flipping halfway.</li><li class='xs-mb2'>Use patties to create your dream veggie burger.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
    "duration": "35 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/video-api-prod/assets/53125c5621bf480d8ae4f02b1cf4ea78/BFV8045_BlackBeanBurgers-Thumb1080B.jpg?resize=600:*&output-format=auto&output-quality=auto","https://www.inspiredtaste.net/wp-content/uploads/2020/02/The-Best-Black-Bean-Burger-Recipe-2-1200.jpg", "https://th.bing.com/th/id/R.0fb0fb77d697cf2be2f815ee6db5c59d?rik=8rSj3J%2fkctpPFg&pid=ImgRaw&r=0"]
},

{
    "name": "Chili Con Carne",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->4<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->olive oil</li><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->onion<!-- -->, chopped</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->red pepper flakes</li><li class='ingredient xs-mb1 xs-mt0'>1 lb <!-- -->ground beef<span class='xs-inline-block xs-ml05'> (<!-- -->400 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>4 cloves <!-- -->garlic<!-- -->, minced</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->brown sugar</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->cumin</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->cilantro powder</li><li class='ingredient xs-mb1 xs-mt0'>3 tablespoons <!-- -->chili powder</li><li class='ingredient xs-mb1 xs-mt0'>3 ½ cups <!-- -->tomato<span class='xs-inline-block xs-ml05'> (<!-- -->796 <!-- -->mL<!-- -->)</span>, diced</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->tomato paste</li><li class='ingredient xs-mb1 xs-mt0'>2 ½ cups <!-- -->red kidney bean<span class='xs-inline-block xs-ml05'> (<!-- -->540 <!-- -->g<!-- -->)</span>, washed and dried</li><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->green pepper<!-- -->, diced</li><li class='ingredient xs-mb1 xs-mt0'>2 cups <!-- -->whole kernel corn<span class='xs-inline-block xs-ml05'> (<!-- -->340 <!-- -->mL<!-- -->)</span></li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>In a large pan, cook the onions and pepper flakes in olive oil until the onions are translucent. Then, add the beef and garlic and saute until cooked.</li><li class='xs-mb2'>Add the brown sugar, cumin, cilantro and chili powder. Mix, then add the diced tomatoes and tomato paste. Lower the heat and simmer for 20 minutes.</li><li class='xs-mb2'>Add the red kidney beans and cool for another 20 minutes.</li><li class='xs-mb2'>Add the green pepper and corn. Simmer together for 5 minutes.</li><li class='xs-mb2'>Serve.</li></ol></div>",
    "duration": "25 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/3c24b556d1c44dbea85b4545502dee99.jpeg?resize=600:*&output-format=auto&output-quality=auto","https://bing.com/th?id=OSK.8c58421c7c70d5d0dde4407cefb162fb", "https://bing.com/th?id=OSK.e3d874d77b8f5b094817dbd669898c81"]
},
{
    "name": "Chocolate-Peppermint Balls",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->15<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>1 ½ cups <!-- -->chocolate chips<span class='xs-inline-block xs-ml05'> (<!-- -->260 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->crushed candy cane<span class='xs-inline-block xs-ml05'> (<!-- -->70 <!-- -->g<!-- -->)</span>, or peppermint rounds</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Melt the chocolate in a microwave until smooth.</li><li class='xs-mb2'>Take out of the microwave and add a splash of water.</li><li class='xs-mb2'>Stir the chocolate until it is a thick consistency and sticks to your spoon.</li><li class='xs-mb2'>Take a small chunk of the chocolate mixture and roll it into a ball with your hands.</li><li class='xs-mb2'>Once you made the ball roll it in your crushed peppermint.</li><li class='xs-mb2'>Chill in the fridge until firm.</li><li class='xs-mb2'>Serve.</li></ol></div>",
    "duration": "15 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/tasty-app-user-assets-prod-us-east-1/recipes/9488486e1c9044cc90b3e959b217c622.jpeg?resize=1000:*&output-format=auto&output-quality=auto","https://bing.com/th?id=OSK.20354189a5d61018afc069b6303e5a2e", "https://bing.com/th?id=OSK.8a291fdd935ee1840dc7470c519d7927"]
},
{
    "name": "Loaded Chicken Enchilada Nachos",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->6<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><p class='ingredient-section-name xs-text-5 extra-bold caps xs-mb1'>Sauce</p><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->vegetable oil</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->flour</li><li class='ingredient xs-mb1 xs-mt0'>2 tablespoons <!-- -->tomato paste</li><li class='ingredient xs-mb1 xs-mt0'>1 ¾ cups <!-- -->chicken stock</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->chili powder</li><li class='ingredient xs-mb1 xs-mt0'>½ teaspoon <!-- -->dried oregano</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->cumin</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->garlic powder</li><li class='ingredient xs-mb1 xs-mt0'>salt<!-- -->, to taste</li><li class='ingredient xs-mb1 xs-mt0'>pepper<!-- -->, to taste</li></ul></div><div class='ingredients__section xs-mt1 xs-mb3'><p class='ingredient-section-name xs-text-5 extra-bold caps xs-mb1'>Nachos</p><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>2 cups <!-- -->shredded chicken<span class='xs-inline-block xs-ml05'> (<!-- -->300 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>tortilla chip</li><li class='ingredient xs-mb1 xs-mt0'>2 cups <!-- -->shredded mexican cheese blend<span class='xs-inline-block xs-ml05'> (<!-- -->200 <!-- -->g<!-- -->)</span></li></ul></div><div class='ingredients__section xs-mt1 xs-mb3'><p class='ingredient-section-name xs-text-5 extra-bold caps xs-mb1'>Garnishes</p><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->sour cream<span class='xs-inline-block xs-ml05'> (<!-- -->115 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>1 <!-- -->tomato<!-- -->, diced</li><li class='ingredient xs-mb1 xs-mt0'>fresh cilantro<!-- -->, optional</li><li class='ingredient xs-mb1 xs-mt0'>queso fresco<!-- -->, optional</li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Heat a small saucepan over medium heat and add the oil and flour. Whisk together and cook gently until it resembles wet sand, about 1 minute.</li><li class='xs-mb2'>Add the tomato paste and whisk. Add chicken stock, chili powder, cumin, garlic powder, oregano, salt and pepper. Stir.</li><li class='xs-mb2'>Bring up to a simmer and cook about 5 minutes until sauce thickens. Remove from heat and set aside. Reserve ½ cup (120 ml).</li><li class='xs-mb2'>Toss the shredded chicken with about ½ cup (120 ml) of the reserved sauce.</li><li class='xs-mb2'>Preheat oven to 400°F (200°C).</li><li class='xs-mb2'>Place a layer of tortilla chips in a skillet or bake dish. Add a layer of cheese and half the chicken mixture. Drizzle some enchilada sauce over the top.</li><li class='xs-mb2'>Add a second layer of tortilla chips followed by another layer of cheese and the remaining chicken. Drizzle with sauce.</li><li class='xs-mb2'>Bake for 8-10 minutes until cheese is melted.</li><li class='xs-mb2'>Top with sour cream, diced tomato, cilantro, and crumbled queso fresco. Serve immediately.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",
    "duration": "20 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/video-api-prod/assets/7c423be848a546fa8c67a4046f422ba3/BFV21165_Loaded_Enchilada_Nachos-THUMB1080.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.2qUJ1QD6OBxrJGzImVI09gHaLH?rs=1&pid=ImgDetMain"]
},
{
    "name": "Paprika Chicken & Rice Bake",
    "ingredients": "<div class='col md-col-4 xs-mx2 xs-pb3 md-mt0 xs-mt2'><h2 class='extra-bold'>Ingredients</h2><p class='servings-display xs-text-2 xs-mb2'>for <!-- -->5<!-- --> <!-- -->servings</p><div class='ingredients__section xs-mt1 xs-mb3'><ul class='list-unstyled xs-text-3'><li class='ingredient xs-mb1 xs-mt0'>5 <!-- -->chicken thighs</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->salt<!-- -->, plus more to taste</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->pepper<!-- -->, plus more to taste</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->paprika</li><li class='ingredient xs-mb1 xs-mt0'>1 teaspoon <!-- -->dried parsley</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->olive oil</li><li class='ingredient xs-mb1 xs-mt0'>1 tablespoon <!-- -->garlic<!-- -->, minced</li><li class='ingredient xs-mb1 xs-mt0'>½ cup <!-- -->red onion<span class='xs-inline-block xs-ml05'> (<!-- -->75 <!-- -->g<!-- -->)</span>, diced</li><li class='ingredient xs-mb1 xs-mt0'>1 cup <!-- -->long grain rice<span class='xs-inline-block xs-ml05'> (<!-- -->200 <!-- -->g<!-- -->)</span></li><li class='ingredient xs-mb1 xs-mt0'>1 ½ cups <!-- -->chicken broth<span class='xs-inline-block xs-ml05'> (<!-- -->360 <!-- -->mL<!-- -->)</span></li></ul></div><div></div></div>",
    "instructions": "<div class='preparation col xs-flex-grow-1 md-col-8 xs-mx2 xs-mb2 xs-mt2 md-mt0'><div class='xs-flex xs-flex-justify-space-between xs-flex-align-center xs-mb1'><h2 class='extra-bold'>Preparation</h2></div><ol class='prep-steps list-unstyled xs-text-3'><li class='xs-mb2'>Preheat oven to 400˚F (200˚C).</li><li class='xs-mb2'>In a large bowl, evenly season chicken thighs with salt, pepper, paprika, and parsley.</li><li class='xs-mb2'>On high, heat olive oil in a oven-proof pot and place chicken thighs, skin-side down, in the hot oil. Cook 5-6 minutes or the thighs develop brown crispy skin and flip over.</li><li class='xs-mb2'>Cook an additional 5-6 minutes to brown the other side and remove from the pot.</li><li class='xs-mb2'>Add the garlic and onions to the pot, and cook until the onions are transparent.</li><li class='xs-mb2'>Pour in the rice and chicken broth to the pot and season with salt and pepper. Stir well, bringing to a boil.</li><li class='xs-mb2'>Add the chicken thighs back into the pot, skin-side up, on top of the rice, bring back to a boil and cover with a lid.</li><li class='xs-mb2'>Bake for 35-40 minutes, or until the rice is fully cooked.</li><li class='xs-mb2'>NOTE: For a crispy skin, remove chicken thighs and broil.</li><li class='xs-mb2'>Enjoy!</li></ol></div>",    
    "duration": "30 minutes",
    "category": "Dinner",
    "images": ["https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/13385.jpg?resize=600:*&output-format=auto&output-quality=auto","https://th.bing.com/th/id/OIP.zSPo-JjRTt4Lk4pLdx_JDQHaEK?rs=1&pid=ImgDetMain", "https://th.bing.com/th/id/OIP.3ZmHNMxdbfMGQ8TyromrRAHaLH?rs=1&pid=ImgDetMain"]
}
]